league_name: Championship
total_games: 46

zones:
  guaranteed:
    Guaranteed Champions:
      cutoff_position: 1
    Guaranteed Promotion:
      cutoff_position: 2
    Guaranteed Play-Offs:
      cutoff_position: 6
    Guaranteed Safety:
      cutoff_position: 21

  predicted:
    Predicted Champions:
      position: 1
    Predicted Promotion:
      cutoff_position: 2
    Predicted Play-Offs:
      cutoff_position: 6
    Predicted Safety:
      cutoff_position: 21
    Predicted Relegation:
      cutoff_position: 22
    
deductions:
  Leicester City: 6
  Sheffield Wednesday: 18

sources:
  table_url: https://www.skysports.com/championship-table